# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinlabApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexmodel',
            name='subject',
            field=models.TextField(max_length=2000),
        ),
    ]
