# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinlabApp', '0002_auto_20170905_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexmodel',
            name='subject',
            field=models.TextField(),
        ),
    ]
