# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinlabApp', '0003_auto_20170905_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexmodel',
            name='subject',
            field=models.CharField(max_length=400),
        ),
    ]
