# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoinlabApp', '0004_auto_20170905_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexmodel',
            name='subject',
        ),
    ]
