# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoinlabApp', '0005_remove_indexmodel_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginmodel',
        ),
    ]
