# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinlabApp', '0007_auto_20180105_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startmodel',
            name='age',
            field=models.IntegerField(max_length=20),
        ),
    ]
