# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoinlabApp', '0008_auto_20180107_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
